on:
  push: 
    branches:
      - master



jobs:
  build:
    runs-on: windows-latest 


    steps:
      - name: 'print folder contents'
        run: ls

      - uses: actions/checkout@v3  

      - name: 'print folder contents'
        run: ls